namespace DevDesk.WinForms.Themes;

public sealed record AppColors(
    Color Background,
    Color Surface,
    Color SurfaceAlt,
    Color Overlay,
    Color Border,
    Color OutlineVariant,
    Color TextPrimary,
    Color TextSecondary,
    Color TextMuted,
    Color Accent,
    Color AccentHover,
    Color AccentSoft,
    Color OnPrimary,
    Color Tertiary,
    Color Success,
    Color Warning,
    Color Error,
    Color ErrorContainer,
    Color SidebarBg,
    Color TopBarBg,
    Color InputBg,
    Color HoverBg,
    Color SelectedBg,
    Color KbdBg);
